sudo: required
dist: bionic
language: csharp
mono: none
dotnet: 3.1.100
solution: Etdb.ReportingService.AspNetCore.sln
env:
  global:
    - DocumentDbContextOptions__ConnectionString="mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@localhost:27017"
    - DocumentDbContextOptions__DatabaseName="Etdb_ReportingService_Travis"
stages:
  - build
  - test
jobs:
  include:
    - stage: build
      name: build solution
      script: dotnet restore && dotnet build
    - stage: test
      name: run-tests
      services:
        - mongodb
        - redis-server
      before_script:
        - sh setup-mongodb-user.sh "$MONGODB_USERNAME" "$MONGODB_PASSWORD"
        - sh scaffold-db.sh
      script: ./run-tests.sh
